Assets/Scripts/Functionality/AudioController.cs
ProjectSettings/ProjectSettings.asset

added audio play on focus

---

Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/SlotBehaviour.cs
Assets/Scripts/UI/UIManager.cs

socket close function added

---

Assets/Scripts/APIs/SocketIOManager.cs

token debug

---

Assets/Plugins/CookieManager.jslib
Assets/Scripts/JS/JSHandler.cs

build cookie fix

---

Assets/Plugins/CookieManager.jslib

cookie manager fix

---

Assets/Advanced WebGL Template/AWT Configurations.asset
Assets/Scripts/APIs/SocketIOManager.cs

Auth token fixed final commit

---

Assets/Scripts/APIs/SocketIOManager.cs

fix socket plugin

---

Assets/Scripts/APIs/SocketIOManager.cs

revert changes in previous commit

revert changes in previous commit

---

Assets/Scripts/APIs/SocketIOManager.cs

Check application load

---

Assets/Scenes/MainScene.unity

socket uri change

---

Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/SlotBehaviour.cs

develop latest fix

---

Assets/Scripts/APIs/SocketIOManager.cs

bets variable fix from int to double

bets variable fix from int to double

---

Assets/Scenes/MainScene.unity
Assets/Scripts/Functionality/SlotBehaviour.cs
ProjectSettings/ProjectSettings.asset

run in background

---

Assets/Scripts/Functionality/SlotBehaviour.cs

win change

---

Assets/Scenes/MainScene.unity
Assets/Scripts/APIs/SocketIOManager.cs

socket changes

---

Assets/Scenes/MainScene.unity
Assets/Scripts/Functionality/BonusController.cs
Assets/Scripts/Functionality/SlotBehaviour.cs

low balance fix

---

Assets/Scenes/MainScene.unity
Assets/Scripts/APIs/SocketIOManager.cs

socket exit message update

---

Assets/Scripts/APIs/SocketIOManager.cs

socket dispose event update

---

Assets/Scripts/Functionality/SlotBehaviour.cs

stop wl audio on focus

---

Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/SlotBehaviour.cs

fix application focus and ping message

fix application focus and ping message

---

Assets/Scenes/MainScene.unity
Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/SlotBehaviour.cs
Assets/Scripts/UI/UIManager.cs

Another device popup implementation and freespins optimised condition

Another device popup implementation and freespins optimised condition

---

Assets/Scenes/MainScene.unity

button anchor fix

---

Assets/Scenes/MainScene.unity

jackpot bonus fix main scene

---

Assets/Scripts/APIs/SocketIOManager.cs

socket final fix

---

Assets/Scripts/APIs/SocketIOManager.cs
ProjectSettings/ProjectSettings.asset

Turned off logs

---

Assets/Scripts/APIs/SocketIOManager.cs

HTTP manager logs disabled

---

Assets/Scripts/Functionality/SlotBehaviour.cs

Free spin num fix

---

Assets/Scenes/MainScene.unity

bonus text fix

---

Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/SlotBehaviour.cs

freespin fix and logs fix

---

Assets/Scripts/APIs/SocketIOManager.cs

websockets logs off trial

---

Assets/Scripts/APIs/SocketIOManager.cs
Assets/WebGLTemplates/AWT/index.html
Packages/com.tivadar.best.http/Runtime/Shared/Logger/ThreadedLogger.cs

logs turn off trial 5

---

Assets/WebGLTemplates/AWT/index.html

turned on logs

---

Assets/Scenes/MainScene.unity
Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/UI/UIManager.cs

dynamic instructions

---

Assets/Scripts/APIs/SocketIOManager.cs

Run time PAR Sheet change commit

Run time PAR Sheet change commit

---

Assets/Scenes/MainScene.unity
Assets/Scripts/Functionality/BonusController.cs
Assets/Scripts/Functionality/SlotBehaviour.cs
Assets/Scripts/UI/ButtonAnimator.cs

Added button audio to the extra buttons added.
Bonus flow changed
Some Bug Fixes

New changes

---

Assets/Scenes/MainScene.unity
Assets/Scripts/APIs/SocketIOManager.cs
Assets/Scripts/Functionality/BonusController.cs
Assets/Scripts/Functionality/SlotBehaviour.cs

- Bonus Start Button Activate When Normal Spin and Auto Start When Auto Spin
- Bonus Slots Values Has To Be Bonus Multiplier * Current Bet Multiplier.

Bonus Modifications Added
